### ISSUE TITLE
Change Rate limit error from HTTP 401 to 429

### ISSUE THREAD

**Issue by colinmcglynn** [OneBusAway/onebusaway-application-modules#190] opened 2016-11-01 18:37 UTC
After the code for this was written a better HTTP error code has been defined 429 (To Many Requests).  We should switch to this so that it is clear to app developers that they are hitting an API limit and not some other error.  Once this change has been made, we can reference this error code in the documentation about rate limits. (See https://github.com/OneBusAway/onebusaway-application-modules/issues/189)

**Comment by sheldonabrown** [comment] 2016-11-01 18:42
For reference, HTTP 401 is currently returned here:
https://github.com/camsys/onebusaway-application-modules/blob/unified/onebusaway-api-webapp/src/main/java/org/onebusaway/api/actions/api/ApiKeyInterceptor.java#L88

After this check fails:
https://github.com/camsys/onebusaway-application-modules/blob/unified/onebusaway-users/src/main/java/org/onebusaway/users/impl/ApiKeyPermissionServiceImpl.java#L45

Trivially an exception could be thrown here to indicate the throttling, but a better solution might be having getPermission return an enum of possible failure reasons.

**Comment by sheldonabrown** [comment] 2016-11-02 17:29
Sound Transit has volunteered to implement the change.

**Comment by barbeau** [comment] 2016-11-02 17:33
That's great! And more accurately it should probably say they they volunteered @sheldonabrown to make the change ;).

**Comment by sheldonabrown** [comment] 2016-11-04 16:35
@barbeau @colinmcglynn I've committed a fix to the camsys repo as that's where ST deploys from.  Once #176  is merged in, it will make it to the OneBusAway repo. 

 Let me know your thoughts.  I added two unit tests to verify the expected behavior.

Since the native OneBusAway applications aren't currently throttled, does it make sense to test them against this change?    

What else should I be worried about when testing this?

**Comment by barbeau** [comment] 2016-11-19 03:20
I would say yes to testing any unthrottled key with this patch, just to make sure nothing strange happens.  Can't think of any other potential issues off the top of my head - I suppose that some clients could be seeing the 401 and backing off (i.e., assuming it's over rate limit), and changing the error code could potentially break that behavior if we start throwing the new error code.  I don't know of anyone doing that, though, and I think the long-term benefits here outweigh any potential short-term consequences.

**Comment by sheldonabrown** [comment] 2017-01-10 18:59
Our QA team pointed out that (as per OBA convention) the OBA API doesn't actually return an HTTP 429 -- its returns an HTTP 200 and then an API code of 429.

Since this is within the convention of OBA and makes it easier for JSON parsers to deal with the result, I'm going to consider this by design.  But its important to call out the difference:
```
wget -S -O - "http://api.staging.obast.org/api/where/schedule-for-stop/1_18406.json?key=TEST" 
HTTP request sent, awaiting response... 
  HTTP/1.1 200 OK
  Server: Apache-Coyote/1.1
  Content-Type: application/json
  Content-Length: 91
  Date: Tue, 10 Jan 2017 18:46:36 GMT
Length: 91 [application/json]
{"code":429,"currentTime":1484073713809,"data":null,"text":"rate limit exceeded","version":1}
```

I fear changing the OBA API to return and HTTP 401/429 would be too large a change to existing applications.

**Closed by sheldonabrown** 2017-01-10 18:59 UTC
Labels: enhancement

**Comment by barbeau** [comment] 2017-01-11 22:28
@sheldonabrown Good point.  I guess at a minimum, though, we should add the  OBA code 429 to the docs here - http://developer.onebusaway.org/modules/onebusaway-application-modules/current/api/where/index.html?

It's currently not listed under "Response Element".  IMHO we should also call the 429 out in a new paragraph under "Response Element" to make it more obvious to clients, as it's currently easy to miss.
